# Yaron: disabled the caching as it is per user caching anyway which does not make sense as updated every x hours

getIcs:
  enabled:    false
#  client_lifetime: 300

all:
  with_layout: false
  lifetime:    3600