<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PartnerDesc', 'doctrine');

/**
 * BasePartnerDesc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $partner_id
 * @property string $description
 * @property integer $category_id
 * @property integer $cal_id
 * @property string $website
 * @property timestamp $updated_at
 * @property Cal $Cal
 * @property Category $Category
 * @property Partner $Partner
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method integer     getPartnerId()   Returns the current record's "partner_id" value
 * @method string      getDescription() Returns the current record's "description" value
 * @method integer     getCategoryId()  Returns the current record's "category_id" value
 * @method integer     getCalId()       Returns the current record's "cal_id" value
 * @method string      getWebsite()     Returns the current record's "website" value
 * @method timestamp   getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Cal         getCal()         Returns the current record's "Cal" value
 * @method Category    getCategory()    Returns the current record's "Category" value
 * @method Partner     getPartner()     Returns the current record's "Partner" value
 * @method PartnerDesc setId()          Sets the current record's "id" value
 * @method PartnerDesc setPartnerId()   Sets the current record's "partner_id" value
 * @method PartnerDesc setDescription() Sets the current record's "description" value
 * @method PartnerDesc setCategoryId()  Sets the current record's "category_id" value
 * @method PartnerDesc setCalId()       Sets the current record's "cal_id" value
 * @method PartnerDesc setWebsite()     Sets the current record's "website" value
 * @method PartnerDesc setUpdatedAt()   Sets the current record's "updated_at" value
 * @method PartnerDesc setCal()         Sets the current record's "Cal" value
 * @method PartnerDesc setCategory()    Sets the current record's "Category" value
 * @method PartnerDesc setPartner()     Sets the current record's "Partner" value
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePartnerDesc extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partner_desc');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('partner_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('category_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('cal_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('website', 'string', 512, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 512,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cal', array(
             'local' => 'cal_id',
             'foreign' => 'id'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('Partner', array(
             'local' => 'partner_id',
             'foreign' => 'id'));
    }
}