<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CalRequest', 'doctrine');

/**
 * BaseCalRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_cal_id
 * @property integer $cal_id
 * @property string $cal_type
 * @property timestamp $created_at
 * @property integer $partner_id
 * @property integer $category_id
 * @property string $hash
 * @property Partner $Partner
 * @property Category $Category
 * @property UserCal $UserCal
 * @property Cal $Cal
 * 
 * @method integer    getId()          Returns the current record's "id" value
 * @method integer    getUserCalId()   Returns the current record's "user_cal_id" value
 * @method integer    getCalId()       Returns the current record's "cal_id" value
 * @method string     getCalType()     Returns the current record's "cal_type" value
 * @method timestamp  getCreatedAt()   Returns the current record's "created_at" value
 * @method integer    getPartnerId()   Returns the current record's "partner_id" value
 * @method integer    getCategoryId()  Returns the current record's "category_id" value
 * @method string     getHash()        Returns the current record's "hash" value
 * @method Partner    getPartner()     Returns the current record's "Partner" value
 * @method Category   getCategory()    Returns the current record's "Category" value
 * @method UserCal    getUserCal()     Returns the current record's "UserCal" value
 * @method Cal        getCal()         Returns the current record's "Cal" value
 * @method CalRequest setId()          Sets the current record's "id" value
 * @method CalRequest setUserCalId()   Sets the current record's "user_cal_id" value
 * @method CalRequest setCalId()       Sets the current record's "cal_id" value
 * @method CalRequest setCalType()     Sets the current record's "cal_type" value
 * @method CalRequest setCreatedAt()   Sets the current record's "created_at" value
 * @method CalRequest setPartnerId()   Sets the current record's "partner_id" value
 * @method CalRequest setCategoryId()  Sets the current record's "category_id" value
 * @method CalRequest setHash()        Sets the current record's "hash" value
 * @method CalRequest setPartner()     Sets the current record's "Partner" value
 * @method CalRequest setCategory()    Sets the current record's "Category" value
 * @method CalRequest setUserCal()     Sets the current record's "UserCal" value
 * @method CalRequest setCal()         Sets the current record's "Cal" value
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCalRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cal_request');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('user_cal_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('cal_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('cal_type', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('partner_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('category_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('hash', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Partner', array(
             'local' => 'partner_id',
             'foreign' => 'id'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('UserCal', array(
             'local' => 'user_cal_id',
             'foreign' => 'id'));

        $this->hasOne('Cal', array(
             'local' => 'cal_id',
             'foreign' => 'id'));
    }
}