<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Mailinglist', 'doctrine');

/**
 * BaseMailinglist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property timestamp $created_at
 * @property timestamp $send_at
 * @property User $User
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method integer     getUserId()     Returns the current record's "user_id" value
 * @method timestamp   getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp   getSendAt()     Returns the current record's "send_at" value
 * @method User        getUser()       Returns the current record's "User" value
 * @method Mailinglist setId()         Sets the current record's "id" value
 * @method Mailinglist setUserId()     Sets the current record's "user_id" value
 * @method Mailinglist setCreatedAt()  Sets the current record's "created_at" value
 * @method Mailinglist setSendAt()     Sets the current record's "send_at" value
 * @method Mailinglist setUser()       Sets the current record's "User" value
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMailinglist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mailinglist');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('send_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}