<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PartnerUser', 'doctrine');

/**
 * BasePartnerUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $partner_id
 * @property integer $user_id
 * @property Partner $Partner
 * @property User $User
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method integer     getPartnerId()  Returns the current record's "partner_id" value
 * @method integer     getUserId()     Returns the current record's "user_id" value
 * @method Partner     getPartner()    Returns the current record's "Partner" value
 * @method User        getUser()       Returns the current record's "User" value
 * @method PartnerUser setId()         Sets the current record's "id" value
 * @method PartnerUser setPartnerId()  Sets the current record's "partner_id" value
 * @method PartnerUser setUserId()     Sets the current record's "user_id" value
 * @method PartnerUser setPartner()    Sets the current record's "Partner" value
 * @method PartnerUser setUser()       Sets the current record's "User" value
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePartnerUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partner_user');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('partner_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Partner', array(
             'local' => 'partner_id',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}