<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserBirthday', 'doctrine');

/**
 * BaseUserBirthday
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $full_name
 * @property string $birthdate
 * @property timestamp $created_at
 * @property User $User
 * 
 * @method integer      getId()         Returns the current record's "id" value
 * @method integer      getUserId()     Returns the current record's "user_id" value
 * @method string       getFullName()   Returns the current record's "full_name" value
 * @method string       getBirthdate()  Returns the current record's "birthdate" value
 * @method timestamp    getCreatedAt()  Returns the current record's "created_at" value
 * @method User         getUser()       Returns the current record's "User" value
 * @method UserBirthday setId()         Sets the current record's "id" value
 * @method UserBirthday setUserId()     Sets the current record's "user_id" value
 * @method UserBirthday setFullName()   Sets the current record's "full_name" value
 * @method UserBirthday setBirthdate()  Sets the current record's "birthdate" value
 * @method UserBirthday setCreatedAt()  Sets the current record's "created_at" value
 * @method UserBirthday setUser()       Sets the current record's "User" value
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserBirthday extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_birthday');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('full_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('birthdate', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}