<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('State', 'doctrine');

/**
 * BaseState
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $country_id
 * @property string $name
 * @property string $regioncode
 * @property Country $Country
 * @property Doctrine_Collection $City
 * @property Doctrine_Collection $User
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getCountryId()  Returns the current record's "country_id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method string              getRegioncode() Returns the current record's "regioncode" value
 * @method Country             getCountry()    Returns the current record's "Country" value
 * @method Doctrine_Collection getCity()       Returns the current record's "City" collection
 * @method Doctrine_Collection getUser()       Returns the current record's "User" collection
 * @method State               setId()         Sets the current record's "id" value
 * @method State               setCountryId()  Sets the current record's "country_id" value
 * @method State               setName()       Sets the current record's "name" value
 * @method State               setRegioncode() Sets the current record's "regioncode" value
 * @method State               setCountry()    Sets the current record's "Country" value
 * @method State               setCity()       Sets the current record's "City" collection
 * @method State               setUser()       Sets the current record's "User" collection
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseState extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('state');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('country_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('regioncode', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id'));

        $this->hasMany('City', array(
             'local' => 'id',
             'foreign' => 'state_id'));

        $this->hasMany('User', array(
             'local' => 'id',
             'foreign' => 'state_id'));
    }
}