<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PaypalIpn', 'doctrine');

/**
 * BasePaypalIpn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $partner_id
 * @property string $ipn_code
 * @property string $transaction_code
 * @property string $status
 * @property string $res_data
 * @property integer $is_test
 * @property timestamp $created_at
 * @property Partner $Partner
 * 
 * @method integer   getId()               Returns the current record's "id" value
 * @method integer   getPartnerId()        Returns the current record's "partner_id" value
 * @method string    getIpnCode()          Returns the current record's "ipn_code" value
 * @method string    getTransactionCode()  Returns the current record's "transaction_code" value
 * @method string    getStatus()           Returns the current record's "status" value
 * @method string    getResData()          Returns the current record's "res_data" value
 * @method integer   getIsTest()           Returns the current record's "is_test" value
 * @method timestamp getCreatedAt()        Returns the current record's "created_at" value
 * @method Partner   getPartner()          Returns the current record's "Partner" value
 * @method PaypalIpn setId()               Sets the current record's "id" value
 * @method PaypalIpn setPartnerId()        Sets the current record's "partner_id" value
 * @method PaypalIpn setIpnCode()          Sets the current record's "ipn_code" value
 * @method PaypalIpn setTransactionCode()  Sets the current record's "transaction_code" value
 * @method PaypalIpn setStatus()           Sets the current record's "status" value
 * @method PaypalIpn setResData()          Sets the current record's "res_data" value
 * @method PaypalIpn setIsTest()           Sets the current record's "is_test" value
 * @method PaypalIpn setCreatedAt()        Sets the current record's "created_at" value
 * @method PaypalIpn setPartner()          Sets the current record's "Partner" value
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePaypalIpn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paypal_ipn');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('partner_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('ipn_code', 'string', 512, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 512,
             ));
        $this->hasColumn('transaction_code', 'string', 256, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 256,
             ));
        $this->hasColumn('status', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('res_data', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('is_test', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Partner', array(
             'local' => 'partner_id',
             'foreign' => 'id'));
    }
}