<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Invitation', 'doctrine');

/**
 * BaseInvitation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $by_user_id
 * @property integer $cal_id
 * @property integer $event_id
 * @property string $email
 * @property timestamp $created_at
 * @property Cal $Cal
 * @property Event $Event
 * @property User $User
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method integer    getByUserId()   Returns the current record's "by_user_id" value
 * @method integer    getCalId()      Returns the current record's "cal_id" value
 * @method integer    getEventId()    Returns the current record's "event_id" value
 * @method string     getEmail()      Returns the current record's "email" value
 * @method timestamp  getCreatedAt()  Returns the current record's "created_at" value
 * @method Cal        getCal()        Returns the current record's "Cal" value
 * @method Event      getEvent()      Returns the current record's "Event" value
 * @method User       getUser()       Returns the current record's "User" value
 * @method Invitation setId()         Sets the current record's "id" value
 * @method Invitation setByUserId()   Sets the current record's "by_user_id" value
 * @method Invitation setCalId()      Sets the current record's "cal_id" value
 * @method Invitation setEventId()    Sets the current record's "event_id" value
 * @method Invitation setEmail()      Sets the current record's "email" value
 * @method Invitation setCreatedAt()  Sets the current record's "created_at" value
 * @method Invitation setCal()        Sets the current record's "Cal" value
 * @method Invitation setEvent()      Sets the current record's "Event" value
 * @method Invitation setUser()       Sets the current record's "User" value
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInvitation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('invitation');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('by_user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('cal_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('event_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cal', array(
             'local' => 'cal_id',
             'foreign' => 'id'));

        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'by_user_id',
             'foreign' => 'id'));
    }
}