<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MailinglistTask', 'doctrine');

/**
 * BaseMailinglistTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mailinglist_id
 * @property timestamp $created_at
 * @property timestamp $send_at
 * @property Mailinglist $Mailinglist
 * 
 * @method integer         getId()             Returns the current record's "id" value
 * @method integer         getMailinglistId()  Returns the current record's "mailinglist_id" value
 * @method timestamp       getCreatedAt()      Returns the current record's "created_at" value
 * @method timestamp       getSendAt()         Returns the current record's "send_at" value
 * @method Mailinglist     getMailinglist()    Returns the current record's "Mailinglist" value
 * @method MailinglistTask setId()             Sets the current record's "id" value
 * @method MailinglistTask setMailinglistId()  Sets the current record's "mailinglist_id" value
 * @method MailinglistTask setCreatedAt()      Sets the current record's "created_at" value
 * @method MailinglistTask setSendAt()         Sets the current record's "send_at" value
 * @method MailinglistTask setMailinglist()    Sets the current record's "Mailinglist" value
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMailinglistTask extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mailinglist_task');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('mailinglist_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('send_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mailinglist', array(
             'local' => 'mailinglist_id',
             'foreign' => 'id'));
    }
}