<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FbUser', 'doctrine');

/**
 * BaseFbUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $full_name
 * @property string $birthdate
 * @property string $fb_code
 * @property timestamp $created_at
 * @property Doctrine_Collection $UserFbUser
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getFullName()   Returns the current record's "full_name" value
 * @method string              getBirthdate()  Returns the current record's "birthdate" value
 * @method string              getFbCode()     Returns the current record's "fb_code" value
 * @method timestamp           getCreatedAt()  Returns the current record's "created_at" value
 * @method Doctrine_Collection getUserFbUser() Returns the current record's "UserFbUser" collection
 * @method FbUser              setId()         Sets the current record's "id" value
 * @method FbUser              setFullName()   Sets the current record's "full_name" value
 * @method FbUser              setBirthdate()  Sets the current record's "birthdate" value
 * @method FbUser              setFbCode()     Sets the current record's "fb_code" value
 * @method FbUser              setCreatedAt()  Sets the current record's "created_at" value
 * @method FbUser              setUserFbUser() Sets the current record's "UserFbUser" collection
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFbUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fb_user');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('full_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('birthdate', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('fb_code', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserFbUser', array(
             'local' => 'id',
             'foreign' => 'fb_user_id'));
    }
}