<?php

/**
 * Address
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Address extends BaseAddress
{

	
	
	public function getForDisplay() {
		$countryCode = $this->getCountryCode();
		$state = $this->getState();
		$city = $this->getCity();
		$addr = $this->getAddr();

		$str = '';
		
		if ($city) $str .= "$city ";
		
		
		if ($state) $str .= " $state, "; 
		$str .= $countryCode;
//		if ($addr) 	$str .= " $addr";
		
		return $str;
		
	}	
}