<?php

/**
 * CalRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CalRequest extends BaseCalRequest
{
   public function getAsCSV() {
        $calReq     = $this;
        
        $d          = $this->getCreatedAt();
        $dt         = new DateTime($d);

        $str = sprintf('%s, %s, %s, %s, %s',
                                        $calReq->getId(),
                                        $calReq->getCalType(),
                                        $dt->format('Y-m-d'),
                                        $calReq->getCal()->getName(),
                                        implode('/',$calReq->getCal()->getCategory()->getCategoryPath())
                                        );
        
        return $str;

    }

}