<?php

/**
 * CategoryLinkUsage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CategoryLinkUsage extends BaseCategoryLinkUsage
{
   public function getAsCSV() {
        $linkUsage     = $this;
        $d          = $this->getCreatedAt();
        $dt         = new DateTime($d);

        $str = sprintf('%s, %s, %s, %s, %s, %s, %s, %s, %s',
                                        $linkUsage->getId(),
                                        $linkUsage->getCategoryLink()->getType(),
                                        $linkUsage->getCategoryLink()->getTxt(),
                                        $linkUsage->getCategoryLink()->getUrl(),
                                        $linkUsage->getCategoryLink()->getTargetUrl(),
                                        $linkUsage->getUserCal()->getCalType(),
                                        implode('/',$linkUsage->getUserCal()->getCal()->getCategory()->getCategoryPath()),
                                        $linkUsage->getUserCal()->getCal()->getName(),
                                        $dt->format('Y-m-d')
                                        );
        
        return $str;

    }

}