<?php

/**
 * CategoryLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CategoryLink extends BaseCategoryLink
{
	
	public function toJSON($calId, $partnerId) {

		$url = GeneralUtils::DOMAIN . "/cal/forwardTo/cal/$calId/link/{$this->getId()}/ref/$partnerId";		
		
		$strJson = '{';
		$strJson .= '"name": "'.$this->getTxt().'"';		
		$strJson .= ',"type": "'.$this->getType().'"';		
		$strJson .= ',"url": "'.$url.'"';		
		$strJson .= '}';
		return $strJson;
		
	}
	public static function makeJSON($calId, $partnerId, $links) {
		// Note: need this space in case that links is empty 
    	$linksJson = '[ ';
        foreach ($links as $link) {
            $linksJson .= $link->toJSON($calId, $partnerId) . ","; 
        }
        $linksJson = substr($linksJson, 0, -1);
        $linksJson .= ']';
        return $linksJson;        
	}	

	
	public function getImgPath() {
		return "/images/links/".$this->getType().".png";	
	}
	
	public function getUrlToGive($calId, $userCalId=null) {
		$url = GeneralUtils::DOMAIN . "/cal/forwardTo/cal/{$calId}/";
		if ($userCalId) {
			$url .= "ucal/{$userCalId}/"; 	
		}
		$url .= "link/{$this->getId()}"; 
		return $url;
	}
	
}