<?php

/**
 * EventStat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EventStat extends BaseEventStat
{
	private $newLine = "\n";
	
	public function getDescriptionForCal($isHtmlSupported = true){
		$partner = UserUtils::getPartner();
		
		$NL = $this->newLine;
		$desc = $NL;
		
		$url = "http://sportYcal.com/l/sportwiser";
		if ($partner && $partner->isWhiteLabel()) {
			$url = "http://sportwiser.com";
		}
		
		$filteredKeys = array();
		if (!$partner || $partner->isRingtonepartner())$filteredKeys = array('OverUnder', 'FirstHalfWinner', 'SecondHalfWinner', 'FirstGoal', 'TimeOfGoals', 'LiveStatistic');
		
		if ($text = self::getText()){
			$text = json_decode($text, true);
			$stat = $text['StatisticsCollection'];
			
			if ($isHtmlSupported){
				foreach ($stat as $key => $vals){
					if (in_array($key, $filteredKeys) ) continue;
					if (!$vals) 						continue;
					$desc .= "<h3 style='color:#3A95D8'>" . $key . "</h3>" . $NL;
					foreach ($vals as $val){
						$val = str_replace('[', '<b>', $val);
						$val = str_replace(']', '</b>', $val);
						$desc .= "<p style='color:#333333'>" . $val . "</p>" . $NL;
					}
					$desc .= '<br/>' . $NL;
				}
				
				$desc .= '<a href="'.$url.'" target="_blank">SportWiser</a>';

			} else {
				foreach ($stat as $key => $vals){
					if (in_array($key, $filteredKeys) ) continue;
					if (!$vals) 						continue;
					$desc .= $key . $NL . $NL;
					foreach ($vals as $val){
						$val = str_replace('[', '', $val);
						$val = str_replace(']', '', $val);
						$desc .= $val . $NL;
					}
					$desc .= $NL . $NL;
				}
				
				$desc .= $url;
			}
		}
		
		return $desc;
	}
}