<?php

/**
 * Intel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Intel extends BaseIntel
{
	public static function reportSrc($section, $src) {
	  	$validSrcs = array("site", "cal-event", "cal-event-desc", "fb", "cw", "fbpr");
	  	if (!in_array($src, $validSrcs)) $src = "";
	  	
	  	IntelTable::insertNew($section, "visit", "src:$src", 0);
	}

}