<?php

/**
 * MailinglistTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailinglistTaskTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailinglistTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MailinglistTask');
    }
    
    public static function getAll($limit=100 ,$openTasks = true){
    	$q = Doctrine::getTable('MailinglistTask')->createQuery('mlt')
    		->innerJoin('mlt.Mailinglist ml')
	    	->limit($limit);
    	 
    	if ($openTasks) $q->where('mlt.send_at IS NULL');
    	 
    	return $q->execute();
    }
    
    public static function clearTasks(){
    	$q = Doctrine_Query::create()
	    	->delete('MailinglistTask m')
	    	->where('m.send_at IS NULL');
    	
    	
    	return $q->execute();
    }
}