<?php

/**
 * MailinglistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailinglistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailinglistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mailinglist');
    }
    
    public static function getAll($page=0, $limit=100 ,$subscribe = true){
    	$offset = $page * $limit;
    	
    	$q = Doctrine::getTable('Mailinglist')->createQuery('m')
    		->offset($offset)
    		->limit($limit);
    	
    	if ($subscribe) $q->where('m.deleted_at IS NULL');
    	
    	return $q->execute();
    }
    
    public static function getBy($email, $calId=null, $ctgId=null){
    	$mailinglist = null;
    	
    	if ($calId || $ctgId){
    		$q = Doctrine::getTable('Mailinglist')
    		->createQuery('m')
    		->where('m.deleted_at is NULL')
    		->andWhere('m.email =?', $email);
    		 
    		if ($calId) $q->andWhere('m.cal_id = ?', $calId);
    		if ($ctgId) $q->andWhere('m.category_id = ?', $ctgId);
    		 
    		$mailinglist = $q->fetchOne();
    	}
    	
    	return $mailinglist;
    }
}