<?php

/**
 * PartnerDesc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PartnerDesc extends BasePartnerDesc
{
	const CTG_ID_SOCCER = 3;
	const CTG_ID_TENNIS = 5;
	const CTG_ID_NBA = 636;
	
	public static function getDescForCal($cal, $calType) {
        
		$desc = '';
		
		if ($cal->getPartnerId()) return $desc;
		
		$showTicket = false;
		$ctgIds = $cal->getCategoryIds();
		
		foreach ($ctgIds as $ctgId){
			if ($ctgId == self::CTG_ID_SOCCER || $ctgId == self::CTG_ID_TENNIS || $ctgId == self::CTG_ID_NBA){
				$showTicket = true;
				break;
			}
		}

		if ($showTicket) {
			// short url to: http://www.sportsevents365.com?a_aid=4f26c59635296&amp;a_bid=204845fd
			$strLink = 'http://sportYcal.com/l/tickets';
        	if (Cal::isHtmlSupported($calType)) {
        		
        		// <strong>Get a ticket!</strong> (Sports Events 365)<br/>
				$strLink = "<a href='$strLink' target='_top'><img src='http://www.sportYcal.com/images/partner/se365banner.jpg' /></a><img style='border:0' src='http://aff.sportsevents365.com/affiliates/scripts/imp.php?a_aid=4f26c59635296&amp;a_bid=204845fd' width='1' height='1' />";
        	} else {
        		$strLink = "Get your ticket here - $strLink"; 
        	}
        	
        	$desc = $strLink;
		}
        
		
        return $desc;
	}		
}