<?php

/**
 * ShortUrl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShortUrl extends BaseShortUrl
{

	public function getShortcut() {
		return GeneralUtils::DOMAIN . '/l/'. $this->getHash();	
	}
	
	
	
	/*
	
	// NEVER CHANGE THIS
	private static $encodeString = 'xv5szfyre9oq1_bhpjanlwgc03+8dimu726tk4';
	// NEVER CHANGE THIS
	
	
	// --------------------------------------------------------------------
	public static function encode_string($num) {
		
		$index = self::$encodeString;
		$base = strlen($index);
		  $out = "";
		  for ( $t = floor( log10( $num ) / log10( $base ) ); $t >= 0; $t-- ) {
				$a = floor( $num / pow( $base, $t ) );
				$out = $out . substr( $index, $a, 1 );
				$num = $num - ( $a * pow( $base, $t ) );
		  }
		  return $out;
	}
	
	// --------------------------------------------------------------------
	public static function decode_string($string) {
	  $index = self::$encodeString;
		$base = strlen($index);
	  $out = 0;
	  $len = strlen( $string ) - 1;
	  for ( $t = 0; $t <= $len; $t++ ) {
		  $out = $out + strpos( $index, substr( $string, $t, 1 ) ) * pow( $base, $len - $t );
	  }
	  return $out;
	}

	
	public static function createHash($shortUrlId) {
		return ShortUrl::encode_string($shortUrlId);
	}

*/	

}