<?php

/**
 * UserSearch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserSearch extends BaseUserSearch
{
   public function getAsCSV() {
        $userSearch = $this;
        $d          = $this->getCreatedAt();
        $dt         = new DateTime($d);

        $str = sprintf('%s, %s, %s, %s',
                                        $userSearch->getId(),
                                        $dt->format('Y-m-d'),
                                        $userSearch->getStr(),
                                        $userSearch->getUserId()
                                        );
        
        return $str;
   }

   
   public function getDateRange() {
   		
   		$fromDate = $this->getFromDate();
   		$toDate   = $this->getToDate();
   		
   		if ($fromDate != '0000-00-00 00:00:00') $fromDate 	= strtotime($this->getFromDate());
   		else  									$fromDate = null;
   		if ($toDate != '0000-00-00 00:00:00') 	$toDate 	= strtotime($this->getToDate());
   		else  									$toDate = null;
		
		if ($fromDate || $toDate) {
			if (!$fromDate) $fromDate = "Any";
			else $fromDate = format_date($fromDate, "p");
			if (!$toDate) 	$toDate = "Any";
			else $toDate = format_date($toDate, "p"); 
			return  $fromDate . " - " . $toDate; 
		} else return "";
   }
   
}