<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User extends BaseUser
{
    public function isMaster() {
        $type = $this->getType();
        return ($type == "MASTER");
    }
    public function isSimple() {
        $type = $this->getType();
        return ($type == "SIMPLE");
    }
    
    public function isPartner() {
        $type = $this->getType();
        return ($type == "PARTNER");
    }
    
}