<?php

/**
 * Wix
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    evento
 * @subpackage model
 * @author     Yaron Biton
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Wix extends BaseWix{
	const DEFAULT_CAL_ID = 9090;
	const DEFAULT_UPCOMING = 5;
	public static $UPCOMING_OPTIONS = array(
		5 => 5,
		10 => 10,
		20 => 20,
		50 => 50		
	);
}