<?php

/**
 * WixTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WixTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WixTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Wix');
    }
    
    public static function getByInstanceCode($instanceCode){
    	$wix = Doctrine::getTable('Wix')
    		->createQuery('w')
    		->where('instance_code =?', $instanceCode)
    		->fetchOne();
    	
    	if (!$wix) {
    		$wix = new Wix();
    		$wix->setCalId(Wix::DEFAULT_CAL_ID);
    		$wix->setUpcoming(Wix::DEFAULT_UPCOMING);
    	}
    	
    	return $wix;
    }
}