# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
dev:
  domain:
    short: sportycal.local
    full:  http://sportycal.local
  facebook:
    appId: 313400138677127
    secret: 62094be3d3db0caf976e93cc44ef7cad
  licensario:
    apiKey: b3448e470128a1fa1e1999f85e2bf1f95e4aa7067f76431645937b1470419926
    apiSecret: b969f923328a2d23db94736a19311b64aeb6edaca9c92f62f51006d83487dd13
    
all:
  licensario:
    apiKey: bc5e3dbd1618ba04fff03d21429692fe1e53553305d7cf4ed257fa1801e2eaaa
    apiSecret: 160fbf80457f30da67fb25ff04ac493f822152d54ecf1eaed9fd0abc1869cb43
  mailinglist:
    fromName: iNeverMiss.biz Support
    fromEmail: support@inevermiss.biz
    replyToName: iNeverMiss.biz Sales
    replyToEmail: sales@inevermiss.biz
  gmail:
    username: test4inevermiss@gmail.com
    password: 123454321Aa
  domain:
    isNeverMiss: false
    isMobile: false
    short: www.sportycal.com
    full:  http://www.sportycal.com
    name: sportYcal
  captha:
    dir: /images/captchas/
    rootDir: %SF_WEB_DIR%/images/captchas/
  spider:
   outputDir: %SF_ROOT_DIR%/test/
  facebook:
    appId: 144339832273543
    secret: 2b3826caa86512d10958465a54de5afb
