# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

ec2:
  domain:
    short: ec2-54-200-96-222.us-west-2.compute.amazonaws.com
    full:  http://ec2-54-200-96-222.us-west-2.compute.amazonaws.com
  facebook:
    appId: 313400138677127
    secret: 62094be3d3db0caf976e93cc44ef7cad
  paypal:
    url: https://www.sandbox.paypal.com
    nvpApiUrl: https://api-3t.sandbox.paypal.com/nvp
    user: il.mrbit.test_api1.gmail.com
    pwd: J5GDNALQRQDTRPUR
    signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A5WRB56.MHOen7D.4UQEzBgUxmEZ
    version: 98
    
dev:
  domain:
    short: sportycal.local
    full:  http://sportycal.local
  facebook:
    appId: 313400138677127
    secret: 62094be3d3db0caf976e93cc44ef7cad
  paypal:
    url: https://www.sandbox.paypal.com
    nvpApiUrl: https://api-3t.sandbox.paypal.com/nvp
    user: il.mrbit.test_api1.gmail.com
    pwd: J5GDNALQRQDTRPUR
    signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A5WRB56.MHOen7D.4UQEzBgUxmEZ
    version: 98
    
all:
  wix:
    appKey : 12e3edc7-b350-5cc8-e263-59d559d56671
    appSecretKey : 8be3c89d-1858-4203-95c1-c3a6bf87034a  
  paypal:
    url: https://www.paypal.com
    nvpApiUrl: https://api-3t.paypal.com/nvp
    user: rami.vachner_api1.sportycal.com
    pwd: MHZETD8UBGR949M3
    signature: AFcWxV21C7fd0v3bYYYRCpSSRl31ABtKzf1Z7rFUmynPPt-wxfTh3EYl
    version: 98
  mailinglist:
    fromName: iNeverMiss.net Support
    fromEmail: support@inevermiss.net
    replyToName: iNeverMiss.net Support
    replyToEmail: support@inevermiss.net
  gmail:
    username: support@inevermiss.net
    password: SportYcal900
  domain:
    isNeverMiss: false
    isMobile: false
    short: www.sportycal.com
    full:  http://www.sportycal.com
    name: sportYcal
  captha:
    dir: /images/captchas/
    rootDir: %SF_WEB_DIR%/images/captchas/
  spider:
   outputDir: %SF_ROOT_DIR%/test/
  facebook:
    appId: 144339832273543
    secret: 2b3826caa86512d10958465a54de5afb
