# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false
    cache:                  true
    web_dir: /var/www

dev:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              true
    no_script_name:         false
    etag:                   false

all:
  .settings:
    i18n: on
    # Form security secret (CSRF protection)
    csrf_secret:            cb8efc0aa91f8d8c516d73df47cc494cb2ff99f0

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    # Yaron:
    standard_helpers:       [Partial, Cache, I18N, Date]
