<?php 

sleep(2);

?>

var strJson = '[ { "id": 11514,"name": "New York Knicks vs. Portland Trail Blazers","starts": "2011-01-11 22:00:00","ends": "2011-01-11 22:00:00","cal": "New York Knicks regular season","calNumEvents": 82,"calUrl": "http://sportYcal.com/cal/43/ref/gpi","ctgPath": "Basketball / NBA / Eastern Division / New York Knicks","ctgImgPath": "/images/categories/basketball_sub1.gif","links": [ {"name": "NBA Basketball Tickets","type": "ticket","url": "http://sportYcal.com/cal/forwardTo/cal/43/link/2/ref/gpi"},{"name": "Web Site","type": "website","url": "http://sportYcal.com/cal/forwardTo/cal/43/link/2109/ref/gpi"}]},{ "id": 11515,"name": "New York Knicks vs. Utah Jazz","starts": "2011-01-12 21:00:00","ends": "2011-01-12 21:00:00","cal": "New York Knicks regular season","calNumEvents": 82,"calUrl": "http://sportYcal.com/cal/43/ref/gpi","ctgPath": "Basketball / NBA / Eastern Division / New York Knicks","ctgImgPath": "/images/categories/basketball_sub1.gif","links": [ {"name": "NBA Basketball Tickets","type": "ticket","url": "http://sportYcal.com/cal/forwardTo/cal/43/link/2/ref/gpi"},{"name": "Web Site","type": "website","url": "http://sportYcal.com/cal/forwardTo/cal/43/link/2109/ref/gpi"}]},{ "id": 11516,"name": "Sacramento Kings vs. New York Knicks","starts": "2011-01-14 19:30:00","ends": "2011-01-14 19:30:00","cal": "New York Knicks regular season","calNumEvents": 82,"calUrl": "http://sportYcal.com/cal/43/ref/gpi","ctgPath": "Basketball / NBA / Eastern Division / New York Knicks","ctgImgPath": "/images/categories/basketball_sub1.gif","links": [ {"name": "NBA Basketball Tickets","type": "ticket","url": "http://sportYcal.com/cal/forwardTo/cal/43/link/2/ref/gpi"},{"name": "Web Site","type": "website","url": "http://sportYcal.com/cal/forwardTo/cal/43/link/2109/ref/gpi"}]}]';

scwHandleSportEvents(strJson);
