userCalsCSVSuccess:
  has_layout: false
userSearchCSVSuccess:
  has_layout: false
calReqsCSVSuccess:
  has_layout: false
linkUsageCSVSuccess:
  has_layout: false
updateStatsSuccess:
  has_layout: false
fSpiderSuccess:
  has_layout: false
 
